# Generated by Django 6.0.3 on 2026-03-14 00:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('medida_unidade', models.CharField(default='kg', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Plantacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talhao', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('rendimento_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('unidade', models.CharField(default='kg', max_length=20)),
                ('preco_padrao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('localizacao', models.CharField(blank=True, max_length=255, null=True)),
                ('area_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AplicacaoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12)),
                ('data_aplicacao', models.DateField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.insumo')),
                ('plantacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicacoes', to='api.plantacao')),
            ],
        ),
        migrations.AddField(
            model_name='plantacao',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.produto'),
        ),
        migrations.AddField(
            model_name='plantacao',
            name='propriedade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantacoes', to='api.propriedade'),
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unidade', models.CharField(max_length=20)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_compra', models.DateField()),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.insumo')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='api.propriedade')),
            ],
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=100)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('valor', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unidade', models.CharField(blank=True, max_length=20, null=True)),
                ('data_leitura', models.DateTimeField()),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras_sensor', to='api.propriedade')),
            ],
            options={
                'ordering': ['-data_leitura'],
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unidade', models.CharField(max_length=20)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_venda', models.DateField()),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.produto')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='api.propriedade')),
            ],
        ),
    ]
