# Generated by Django 6.0.3 on 2026-03-14 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_add_sensor_reading'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SensorReading',
        ),
    ]
