# Generated by Django 6.0.3 on 2026-03-22 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_sensor_reading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('severidade', models.CharField(choices=[('info', 'Informação'), ('aviso', 'Aviso'), ('critico', 'Crítico')], default='aviso', max_length=10)),
                ('codigo', models.CharField(blank=True, db_index=True, help_text='Chave lógica para evitar duplicatas (ex.: regra financeira diária).', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lido', models.BooleanField(default=False)),
                ('propriedade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='api.propriedade')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-created_at'],
            },
        ),
    ]
