# Generated by Django 6.0.3 on 2026-03-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_tenants', models.PositiveIntegerField(blank=True, help_text='Máximo de inquilinos (vazio = sem limite).', null=True)),
                ('max_users_per_tenant', models.PositiveIntegerField(blank=True, help_text='Máximo de usuários por schema de tenant (vazio = sem limite).', null=True)),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Se ativo, usuários não-staff recebem 503 nas rotas de tenant.')),
                ('maintenance_message', models.TextField(blank=True, default='Plataforma em manutenção. Tente novamente em instantes.')),
                ('allow_new_user_registration', models.BooleanField(default=True, help_text='Permite auto-registro em /registrar/ nos domínios de tenant.')),
            ],
            options={
                'verbose_name': 'Configuração global',
                'verbose_name_plural': 'Configuração global',
            },
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Inquilino (fazenda)', 'verbose_name_plural': 'Inquilinos (fazendas)'},
        ),
        migrations.AlterModelOptions(
            name='domain',
            options={'verbose_name': 'Domínio', 'verbose_name_plural': 'Domínios'},
        ),
    ]
