# Tratemento de endpoints.
from django.urls import path

from . import views_web

urlpatterns = [
    path("propriedades/", views_web.PropriedadeListView.as_view(), name="propriedade_list"),
    path("propriedades/nova/", views_web.PropriedadeCreateView.as_view(), name="propriedade_create"),
    path("propriedades/<int:pk>/editar/", views_web.PropriedadeUpdateView.as_view(), name="propriedade_update"),
    path("propriedades/<int:pk>/excluir/", views_web.PropriedadeDeleteView.as_view(), name="propriedade_delete"),
    path("produtos/", views_web.ProdutoListView.as_view(), name="produto_list"),
    path("produtos/novo/", views_web.ProdutoCreateView.as_view(), name="produto_create"),
    path("produtos/<int:pk>/editar/", views_web.ProdutoUpdateView.as_view(), name="produto_update"),
    path("produtos/<int:pk>/excluir/", views_web.ProdutoDeleteView.as_view(), name="produto_delete"),
    path("insumos/", views_web.InsumoListView.as_view(), name="insumo_list"),
    path("insumos/novo/", views_web.InsumoCreateView.as_view(), name="insumo_create"),
    path("insumos/<int:pk>/editar/", views_web.InsumoUpdateView.as_view(), name="insumo_update"),
    path("insumos/<int:pk>/excluir/", views_web.InsumoDeleteView.as_view(), name="insumo_delete"),
    path("plantacoes/", views_web.PlantacaoListView.as_view(), name="plantacao_list"),
    path("plantacoes/nova/", views_web.PlantacaoCreateView.as_view(), name="plantacao_create"),
    path("plantacoes/<int:pk>/editar/", views_web.PlantacaoUpdateView.as_view(), name="plantacao_update"),
    path("plantacoes/<int:pk>/excluir/", views_web.PlantacaoDeleteView.as_view(), name="plantacao_delete"),
    path("compras/", views_web.CompraListView.as_view(), name="compra_list"),
    path("compras/nova/", views_web.CompraCreateView.as_view(), name="compra_create"),
    path("compras/<int:pk>/editar/", views_web.CompraUpdateView.as_view(), name="compra_update"),
    path("compras/<int:pk>/excluir/", views_web.CompraDeleteView.as_view(), name="compra_delete"),
    path("vendas/", views_web.VendaListView.as_view(), name="venda_list"),
    path("vendas/nova/", views_web.VendaCreateView.as_view(), name="venda_create"),
    path("vendas/<int:pk>/editar/", views_web.VendaUpdateView.as_view(), name="venda_update"),
    path("vendas/<int:pk>/excluir/", views_web.VendaDeleteView.as_view(), name="venda_delete"),
    path("aplicacoes/", views_web.AplicacaoListView.as_view(), name="aplicacao_list"),
    path("aplicacoes/nova/", views_web.AplicacaoCreateView.as_view(), name="aplicacao_create"),
    path("aplicacoes/<int:pk>/editar/", views_web.AplicacaoUpdateView.as_view(), name="aplicacao_update"),
    path("aplicacoes/<int:pk>/excluir/", views_web.AplicacaoDeleteView.as_view(), name="aplicacao_delete"),
    path("alertas/", views_web.AlertaListView.as_view(), name="alerta_list"),
    path("alertas/<int:pk>/lido/", views_web.alerta_marcar_lida_view, name="alerta_marcar_lida"),
    path("relatorios/exportar/csv/", views_web.relatorio_export_csv_view, name="relatorio_export_csv"),
    path("relatorios/exportar/pdf/", views_web.relatorio_export_pdf_view, name="relatorio_export_pdf"),
    path("relatorios/", views_web.relatorios_view, name="relatorios"),
]
